### ISSUE TITLE
How to encrypt a previous sqlite database?

### ISSUE THREAD

**Issue by kazyamof** [davidmartos96/sqflite_sqlcipher#20] opened 2020-05-26 17:22 UTC
My app already has a sqlite database created using SQLiteStudio. 
I would like to encrypt it, and then start to using sqlcipher on my next release build.
Is it possible? How to?

**Comment by davidmartos96** [comment] 2020-05-26 17:31
If you don't need to migrate user information you just need to delete the previous database file and recreate it again using the plugin.
If you need to keep the information saved in the tables, you can take a look at this post, from the SqlCipher forum. I've never tried to encrypt a plain database inside an app, but I have done so using bash scripts on desktop, so it should be doable.
Here is the post: https://discuss.zetetic.net/t/how-to-encrypt-a-plaintext-sqlite-database-to-use-sqlcipher-and-avoid-file-is-encrypted-or-is-not-a-database-errors/868

In theory it should work by first, opening the plain database using an empty password, and then running the following PRAGMA statements. ` encrypted.db` would be the generated encrypted database.
```
ATTACH DATABASE 'encrypted.db' AS encrypted KEY 'newkey';
SELECT sqlcipher_export('encrypted');
DETACH DATABASE encrypted;
```
After that you could delete the plain db and rename the encrypted one to the original name.

Read the post for more information on the topic.

**Comment by davidmartos96** [comment] 2020-05-30 14:37
@kazyamof How did it go? Can I close this?

**Closed by davidmartos96** 2020-05-30 14:37 UTC

**Comment by kazyamof** [comment] 2020-05-30 16:41
I was able to create a database encrypted from scratch. 

void open() async {
    try {
      var databaseName = 'mydb.db';
      var databasePath = await getDatabasesPath();
      var fileDatabaseDir = join(databasePath, databaseName);

      Database database = await openDatabase(fileDatabaseDir, version: 1, password: '123',
          onCreate: (Database db, int version) async {
        await db.execute(
            'CREATE TABLE Test (id INTEGER PRIMARY KEY, name TEXT, value INTEGER, num REAL)');
      });
      // Insert some records in a transaction
      await database.transaction((txn) async {
        int id1 = await txn.rawInsert(
            'INSERT INTO Test(name, value, num) VALUES("some name", 1234, 456.789)');
        print('inserted1: $id1');
        int id2 = await txn.rawInsert(
            'INSERT INTO Test(name, value, num) VALUES(?, ?, ?)',
            ['another name', 12345678, 3.1416]);
        print('inserted2: $id2');
      });

      List<Map> list = await database.rawQuery('SELECT * FROM Test');
      print(list);

      print('Version: ${database.getVersion()}');

      await database.close();
    } catch (e) {
      print('ERROR: $e');
    }
  }

Then, I ran some commands on windows console to extract the .db file:

- adb shell rm -rf /sdcard/rpgapp
- adb shell run-as com.example.encrypted_database cp -r /data/data/com.example.encrypted_database/databases/. /sdcard/rpgapp
- adb pull /sdcard/rpgapp ./
- adb pull /sdcard/rpgapp C:\Repo\

Then, I tried to open the encrypted database file "mydb.db" on SQLiteStudio and SQLiteExpert, without success. Which is the expected behaviour, since the file is encrypted.
![image](https://user-images.githubusercontent.com/3179898/83333430-b7b2a400-a276-11ea-9646-35e842efea8a.png)

The only  drawback  is that I'm used to manage my database entirelly from external tools like SQLiteStudio, and then just copying it from assets folder's project.

With this approach of using sqlite_cipher,  I will need to have an parallel project, just to manage the table creation and initial data insert, and then proceed with this steps of copying the database file from Android Emulator to Windows, and then putting inside /assets of my real app.

**Comment by kazyamof** [comment] 2020-05-30 16:42
> 
> 
> If you don't need to migrate user information you just need to delete the previous database file and recreate it again using the plugin.
> If you need to keep the information saved in the tables, you can take a look at this post, from the SqlCipher forum. I've never tried to encrypt a plain database inside an app, but I have done so using bash scripts on desktop, so it should be doable.
> Here is the post: https://discuss.zetetic.net/t/how-to-encrypt-a-plaintext-sqlite-database-to-use-sqlcipher-and-avoid-file-is-encrypted-or-is-not-a-database-errors/868
> 
> In theory it should work by first, opening the plain database using an empty password, and then running the following PRAGMA statements. ` encrypted.db` would be the generated encrypted database.
> 
> ```
> ATTACH DATABASE 'encrypted.db' AS encrypted KEY 'newkey';
> SELECT sqlcipher_export('encrypted');
> DETACH DATABASE encrypted;
> ```
> 
> After that you could delete the plain db and rename the encrypted one to the original name.
> 
> Read the post for more information on the topic.

I will need more time to test this approach.

**Comment by davidmartos96** [comment] 2020-05-30 16:53
If you are copying a new db from assets on every app update, it's easier that that. You can create you db unencrypted from windows and then encrypt it with a script to then copy the file in your flutter project. That is what I do on my app.

**Comment by kazyamof** [comment] 2020-05-30 17:40
> 
> 
> If you are copying a new db from assets on every app update, it's easier that that. You can create you db unencrypted from windows and then encrypt it with a script to then copy the file in your flutter project. That is what I do on my app.

Could you give me a example of how to encrypt it?
Is the code and forum thread you have mentioned above?

> ATTACH DATABASE 'encrypted.db' AS encrypted KEY 'newkey';
> SELECT sqlcipher_export('encrypted');
> DETACH DATABASE encrypted;

**Comment by davidmartos96** [comment] 2020-05-30 17:55
Yes, is like it is posted in the forum. This is the bash script I use. You can adapt it to your needs. It encrypts the db file passed as argument in a new file named encrypted.db and then it copies it to your flutter assets folder.

```
#!/bin/bash
if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit
fi

echo "Encrypting $1"
rm encrypted.db
echo "ATTACH DATABASE 'encrypted.db' AS encrypted KEY 'mypassword'; SELECT sqlcipher_export('encrypted'); DETACH DATABASE encrypted;" | sqlcipher $1

echo
echo "Copying to Flutter project"
rm flutterprojectpath/dbname.db

cp encrypted.db flutterprojectpath/dbname.db
rm encrypted.db

echo "Done."
```

**Comment by MojtabaTavakkoli** [comment] 2020-06-06 17:14
> 
> 
> Yes, is like it is posted in the forum. This is the bash script I use. You can adapt it to your needs. It encrypts the db file passed as argument in a new file named encrypted.db and then it copies it to your flutter assets folder.
> 
> ```
> #!/bin/bash
> if [ -z "$1" ]
>   then
>     echo "No argument supplied"
>     exit
> fi
> 
> echo "Encrypting $1"
> rm encrypted.db
> echo "ATTACH DATABASE 'encrypted.db' AS encrypted KEY 'mypassword'; SELECT sqlcipher_export('encrypted'); DETACH DATABASE encrypted;" | sqlcipher $1
> 
> echo
> echo "Copying to Flutter project"
> rm flutterprojectpath/dbname.db
> 
> cp encrypted.db flutterprojectpath/dbname.db
> rm encrypted.db
> 
> echo "Done."
> ```

Is there any script or command for windows to do so?
Any link to helpful tutorial is also welcome 😅

**Comment by davidmartos96** [comment] 2020-06-06 17:27
I don't have much experience with Windows bat scripts. I don't think this script would be much different in windows. If you don't feel like porting it you can download Git Bash for windows and use the script from Git-Bash console on Windows.

**Comment by MojtabaTavakkoli** [comment] 2020-06-06 19:12
> 
> 
> I don't have much experience with Windows bat scripts. I don't think this script would be much different in windows. If you don't feel like porting it you can download Git Bash for windows and use the script from Git-Bash console on Windows.

 sqlcipher: command not found.
where should I open gitbash?

1. I cloned the sqlcipher from here: `git clone https://github.com/sqlcipher/sqlcipher.git`
2. In the downloaded folder (sqlcipher) I opened gitbash.
3. but when trying to use that script facing the error `sqlcipher: command not found`

**Comment by davidmartos96** [comment] 2020-06-06 19:45
@MojtabaTavakkoli That is just the source code repository for SQLCipher. On Windows you need to build the sqlcipher executable yourself. 
You can follow this video https://www.youtube.com/watch?v=SFHGeetZ0po

On Linux or macOS is as simple as installing the sqlcipher package. After compiling it on windows, A sqlcipher.exe file is generated, which you then could add to the PATH so that the script is able to find the command.

**Comment by daybson** [comment] 2020-09-22 19:39
> 
> 
> @MojtabaTavakkoli That is just the source code repository for SQLCipher. On Windows you need to build the sqlcipher executable yourself.
> You can follow this video https://www.youtube.com/watch?v=SFHGeetZ0po
> 
>After compiling it on windows, A sqlcipher.exe file is generated, which you then could add to the PATH so that the script is able to find the command.

Hey I'm back. I did the compialtion proccess on Windows, just like the video does,  but I've got genereted an "sqlite3.exe" file, not a sqlcipher.exe.

![image](https://user-images.githubusercontent.com/3179898/93928849-5618b880-fcf1-11ea-9d09-a7b9d7daefd1.png)


If I run the exe, it seems to open ok.
![image](https://user-images.githubusercontent.com/3179898/93928980-86f8ed80-fcf1-11ea-9877-c8a69aa55dab.png)

But even if I add the path "C:\Repositorios\sqlitecipher\sqlcipher" on the PATH system variable (Environment Options/System Variables -> PATH) , I'm still getting the message  _"sqlcipher: command not found"_...

Any hint about this?

**Comment by davidmartos96** [comment] 2020-09-22 19:48
you can rename sqlite3.exe to sqlcipher.exe, or change the script to call sqlite3, that is up to you :smile:

**Comment by daybson** [comment] 2020-09-22 20:37
> 
> 
> You can rename sqlite3.exe to sqlcipher.exe, or change the script to call sqlite3, that is up to you 😄

Almost working now, just getting the error when I ran your script:

```
#!/bin/bash
if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit
fi
 
echo "Encrypting $1"
rm my_app_database.db
echo "ATTACH DATABASE 'my_app_database.db' AS encrypted KEY '123456ABC'; SELECT sqlcipher_export('encrypted'); DETACH DATABASE encrypted;" | sqlite3 $1

echo
echo "Copying to Flutter project"
rm C:/Repositorios/getx/app/app_mobile/assets/databases/my_app_database.db

cp my_app_database.db C:/Repositorios/getx/app/app_mobile/assets/databases/my_app_database.db
rm my_app_database.db

echo "Done."
```

**Error: near line 1: database is locked.**

**Comment by davidmartos96** [comment] 2020-09-22 20:57
@daybson Not sure what the issue would be. I'm using SqlCipher on Linux. Are you using bash to run the script?
You can try experimenting what fails by running it yourself on your command interpreter.
The important line is the following:
`echo "ATTACH DATABASE 'encrypted.db' AS encrypted KEY 'mypassword'; SELECT sqlcipher_export('encrypted'); DETACH DATABASE encrypted;" | sqlcipher unencrypted.db`

How are you running the command? You need to attach a database with a different name from the one provided as argument.

**Comment by daybson** [comment] 2020-09-22 21:03
@MojtabaTavakkoli
I running on Windows using Git Bash.
The bash script is in a file called "bash_build.sh"

I'm oppening a new Git Bash cmd on the same folder as the "bash_build.sh".
I also have a copy of the original database (the one that contains the non encrypted data) on this same folder.

Then I type the commands on Git cmd: 
`./bash_build.sh my_app_database.db`

The behaviour I see is:
The local database file is deleted (I did a backup at another place before!), 
The original database in my C:/Repositorios/getx/app/app_mobile/assets/databases/ is deleted and another one is created, but with 0kb.

**Comment by davidmartos96** [comment] 2020-09-22 21:08
@daybson I think the problem is that you are naming the attached database the same as the unencrypted db (my_app_database.db)
Replace 
ATTACH DATABASE 'my_app_database.db' AS encrypted
with
ATTACH DATABASE 'encrypted.db' AS encrypted

Then you will have the unencrypted database and encrypted database in separate files

**Comment by davidmartos96** [comment] 2020-09-22 21:15
@daybson Also, I see that the output shows a PRAGMA timeout. That shouldn't be needed.

**Comment by daybson** [comment] 2020-09-22 21:25
@davidmartos96 
> @daybson Also, I see that the output shows a PRAGMA timeout. That shouldn't be needed.

I was trying some solutions I've seen around...

Ok, now I'm getting some results!!!

My original file is 720kb, and I'm getting a 724kb file!
Final script:

```
#!/bin/bash
if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit
fi

echo "Encrypting $1"
#rm my_app_database.db
echo "ATTACH DATABASE 'encrypted.db' AS encrypted KEY '123456ABC'; SELECT sqlcipher_export('encrypted'); DETACH DATABASE encrypted;" | sqlite3 $1

echo
echo "Copying to Flutter project"
rm C:/Repositorios/getx/rpg3dit_crudpersonagem_cypher/app_mobile/assets/databases/my_app_database.db

cp encrypted.db C:/Repositorios/getx/rpg3dit_crudpersonagem_cypher/app_mobile/assets/databases/my_app_database.db
rm my_app_database.db

echo "Done."

```

I have to test on the app now, to see if I will get the right data when I use the password. 
I will reply here again!
Thank you @davidmartos96 and @MojtabaTavakkoli  for the attention!

Obs: Do you know if there is some application like SQLiteStudio that is able to open this encrypted sqlite files?

**Comment by davidmartos96** [comment] 2020-09-22 21:30
@daybson Glad you got it working! 
I use SqliteBrowser https://sqlitebrowser.org/
After downloading, on Windows you have 2 different .exe to open the app. One is for opening encrypted databases, which will ask for a password.
In any case, I'd recommend using the unencrypted database when playing with it on desktop for convenience. And then just use the encrypted one on the Flutter app with the help of the script. :wink:

**Comment by daybson** [comment] 2020-09-22 21:54
My app failed when I ommited the password parameter at openDatabase or when I passed a wrong key, which is the expected behaviou! \o/

When I passed the correct key (123456ABC like the script above), did opened and got the data just fine!

Tested on both Android Emulator and android physical device (Android 8.1)
Latter I will test on iPhone Simulator at macOS too.

**Comment by daybson** [comment] 2020-09-23 00:29
I can confirm that **is working on iOS** testing on iPhone SE 2nd Gen Simulator
Running on MacOS Catalina 10.15.6

**Comment by davidmartos96** [comment] 2021-06-03 06:48
@iampopal I wouldn't download any dll from those kind of websites, watch out for that. I'd recommend that you follow the compilation instructions and do it yourself.
You can check the following thread, in particular this comment. It could help you out regarding compilation on Windows
https://github.com/davidmartos96/sqflite_sqlcipher/issues/20#issuecomment-697051979
