### ISSUE TITLE
warning: [deprecation] Registrar in PluginRegistry has been deprecated

### ISSUE THREAD

**Issue by Chakib-Temal** [davidmartos96/sqflite_sqlcipher#50] opened 2021-09-06 11:20 UTC
there is a Warning when compiling project 
 
/Users/xxx/.pub-cache/hosted/pub.dartlang.org/sqflite_sqlcipher-2.0.0/android/src/main/java/com/davidmartos96/sqflite_sqlcipher/SqfliteSqlCipherPlugin.java:37: warning: [deprecation] Registrar in PluginRegistry has been deprecated

import io.flutter.plugin.common.PluginRegistry.Registrar;

in my pubspec.yaml 
sqflite_sqlcipher: 2.0.0

Flutter version : Flutter 2.2.3 • channel stable 
Framework • revision f4abaa0735 (10 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4

**Comment by davidmartos96** [comment] 2021-09-06 11:32
Duplicate of : https://github.com/davidmartos96/sqflite_sqlcipher/issues/49
You can safely ignore the warning. The library is already using the non deprecated method, but there is still code to make it work with old versions of Flutter, hence the warning.
This code will be removed once it gets removed from the Flutter framework

**Closed by davidmartos96** 2021-09-06 11:32 UTC
